version: '3.3'

services:
  nexus:
    image: sonatype/nexus3:3.6.0
    ports: [ "8081:8081", "8082:8082" ]
    deploy:
        placement:
          constraints:
          - node.role == worker
    volumes:
    - nexus-data:/nexus-data

  jenkins:
    image: username/jenkins
    ports: [ "8280:8080" ]
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
    - jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock 

  gitlab:
      image: gitlab/gitlab-ce:8.5.8-ce.0
      ports: [ "8180:80", "8122:22" ]
      deploy:
        placement:
          constraints:
          - node.role == worker
      volumes:
      - gitlab-conf:/etc/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      environment:
      - GITLAB_ROOT_PASSWORD=aqwzsx12341

volumes:
  nexus-data:
  jenkins:
  gitlab-conf:
  gitlab-log:
  gitlab-data:
